# -*- coding: utf-8 -*-

VCS_COLUMNS = [
    "operInstId",
    "regDd",
    "fundNm",
    "formTotamt",
    "prsntInvstAmt",
    "comIndCd",
    "comIndNm",
    "invstPd",
    "continPd",
    "operInstNm",
    "repNm",
    "repTelNo",
    "headofcAddr",
    "headofcDtlAddr",
    "operBoundAmt",
    "sidoNm",
    "pageParamName",
    "pageSize",
    "offset",
    "startRow",
    "endRow",
    "paging",
    "exclusion",
    "repEmail",
    "hpage",
    "투자분야",
    "펀드명_분리",
    "펀드명_원문",
]
